### ISSUE TITLE
[MILESTONE CHECKLIST] Complete prototype the Our Handbook template.

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/our-handbook-template#1]
A full list of everything we'd like in the full handbook! Look here for general inspiration on what to work on (unrelated to specific events).

## Setup
- [x] GitHub infrastructure (#7)
   - [x] Issue templates for instanced book (#16)
- [x] Jupyter Book infastructure:
  - [x] Basics (#8)

## Create sections for the following pages
Here's a list of potential sections for the handbook
- [ ] Welcome (#9)
  - [ ] Update the links in the note.
- [ ] Our research environment (define research culture/environment).
    - [ ] Our physical/digital environment (core hours? city stuff? uni stuff? part time?)
    - [ ] Our values (#10)
    - [ ] Our chosen tools (#5)
    - [ ] Our research interests (#11)
    - [ ] Our activities (#12)
    - [ ] Our roadmap (#6)
- [ ] Our team (#18)
   - [ ] Team members (incl. social media, etc, something fun/a quote, links to projects worked on)
   - [ ] Skills and strengths
   - [ ] Past team members
   - [ ] Joining our team
- [ ] Roles and responsibilities
   - [ ] Shared responsibilities (e.g. administration like organising group meetings or coffee breaks)
   - [ ] Research Internships
   - [ ] Academic group
     - [ ] PhD guide
     - [ ] Postdoc guide
     - [ ] Principal Investigator(s) 
     - [ ] Group leader 
   - [ ] Research Software Engineering group
     - [ ] RSE
     - [ ] Senior RSE
     - [ ] Lead RSE
   - [ ] Extra roles (e.g. maintaining GitHub repos, the group website, the handbook, first aid, fire steward, etc).
- [ ] Projects (project overview from roadmap)
    - [ ] New (but definitely happening) projects
    - [ ] Ongoing projects
    - [ ] Past projects
- [ ] How we work
    - [ ] Coffee breaks
    - [ ] Group meetings (#14)
    - [ ] Journal clubs
    - [ ] Away days
    - [ ] Conferences and other talks
    - [ ] Publishing
    - [ ] Research practices
        - [ ] Reproducibility
        - [ ] Software engineering practices
    - [ ] Group side projects (away "weeks")
    - [ ] One-to-ones
    - [ ] Annual reviews
       - [ ] Template for staff annual review (#3)
       - [ ] Template for PhD annual review (#4)
    - [ ] Other stuff (e.g. hackathons, teaching, extra work, outreach, etc).
- [ ] Useful resources
   - [ ] New team member checklist (#13)
   - [ ] Running a project (flow-chart)
       - [ ] Ethics
       - [ ] Working "open" #30
       - [ ] Working reproducibly
       - [ ] Git/GitHub
           - [ ] Template data analysis repository
           - [ ] Template software repositories (one per language)
       - [ ] Testing
       - [ ] Continuous integration
       - [ ] Documentation
   - [ ] Credit + contributions
   - [ ] Applying for grants/funding
   - [ ] Wellbeing
        - [ ] Email charter
        - [ ] University Resources
        - [ ] Nice walks nearby
   - [ ] Time management #31
      - [ ] Prioritising
        - [ ]  Eisenhower matrix
        - [ ] Mental Inventory (https://bulletjournal.com/blogs/bulletjournalist/mental-inventory) 
      - [ ] Pomodoro technique
      - [ ] Co-working/working meetings
   - [ ] Running Events
        - [ ] Tick list
        - [ ] Code of conduct
- [ ] Glossary (group jargon and acronyms)

---

## Small other to-dos
- [ ] Check all the links `jupyter-book build mybookname/ --builder linkcheck`
- [ ] Update the link in `_config.yml` extra_navbar to be the deployed Our Meta Handbook
