### ISSUE TITLE
 New team member checklist

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/our-handbook-template#13]
- [ ] Familiarise yourself with the team values
   - [ ] (For fun) take any pledges!
- [ ] Prepare a talk for your Welcome morning
- [ ] Go to the staff welcome fair.
- [ ] Book one-to-ones with everyone (or every relevant to you) person in the team. Figure out what they do.
- [ ] Go to meet other teams across the University
- [ ] Book one-to-ones with every relevant person on your project.
- [ ] Follow your team on (work-related) social media. Make yourself a twitter if you want one.
