### ISSUE TITLE
[NEW TEMPLATE SECTION] :sparkles: Our Team

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/our-handbook-template#18]
**What's your idea for the new book section?**
A template for all about the team

**Where should it go in the book?**
See  #1 

**Is this information available anywhere else?**
Not yet

**Why would this section be useful?**
- To help team members know who to ask about what
- To introduce people outside our group to our team members
- To help new team members learn to edit the book

**To-do list**
- [ ] Basics
  - [ ] Names
  - [ ] photos
  - [ ] contact details
  - [ ] social media links
- [ ] Talk to me about
  - [ ] current projects (linking to other parts of the book)
  - [ ] past projects (linking to other parts of the book)
  - [ ] favourite tools/knowledge
  - [ ] fun thing
- [ ] Past team members
- [ ] Joining our team
- [ ] Working with us

**Comment by jcolomb** [comment]
nice would be to get orcid, and fetch some data directly from orcid (name, contact,...)

Also, it would make this legal: indeed if you ask for people name and email (=personal data), you need to be GDPR compliant, something that could make things complex. (while GDPR compliance isa problem of orcid in the other scenario).

**Comment by ekuw** [comment]
I'm going to start adding some templates to the Our Team section for adding team member profiles to the page.

**Comment by mlagisz** [comment]
It would be a good practice to have members ORCIDs included, as well as a placeholder for links to their profiles on other  platforms, e.g. Scopus, Mendeley, ReseachGate, LinkedIn
