### ISSUE TITLE
[TEMPLATE SECTION] Our roadmap

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/our-handbook-template#6]
This section should be about how the group knows:
- [ ] What the plans for the lab are going forwards
- [ ] What the "big picture" is for each lab member, what projects are starting/finishing/might be starting.
- [ ] How the lab fits together. Who shares research interests?
- [ ] How our work aligns with our values. Is there anything we should be trying to do more/less of?
- [ ] What our goals are for the coming 6 months, year, 5 years.

Ideas:
- [ ] Why
    - [ ] By being in this lab, we want to teach you about how to do science, but we also want to teach you how to run a lab: how to get funding, how to publish
   - [ ] We want to be able to support each other in our future career goals, whether in or out of academia. 
    - [ ] We want you to know about any planned big moves (e.g. PI moving), change in research direction, etc.
    - [ ] We want to make sure that we all keep focused on the "big picture": we hear about the intracies of our work at group meetings (which is great), but we want to be able to tell other people about the cool work that happens in our lab.
    - [ ] We want to know how we all fit together, so that we all feel less isolated and more like a team
    - [ ] And maybe we want an excuse to show some of our personal lives (what we like to do for fun, etc) - you are always entitled to privacy, share as much or as little as you'd like.
- [ ] How
    - [ ] State of the lab address: https://sociobiology.wordpress.com/2013/01/24/give-a-state-of-the-lab-address/
    - [ ] Update the lap roadmap every 6 months? (In the handbook? On the group website?)
    - [ ] Group goals (make joint group goals - which go in this section for the next 6 months, and try to do them, e.g. publish more preprints, do a registered report, public outreach). Maybe separate into standing goals and current/specific.
    - [ ] Group reporting?
        - [ ] Grants, e.g. applied for, got, rejected, completed, (cash amounts). Every failed grant box (George Davey Smith).
        - [ ] Publishing. Where? How long? Rejections? Rounds of reviews?
